# SPDX-License-Identifier: GPL-2.0-or-later
#
# Makefile for QUIC support code.
#

obj-$(CONFIG_IP_QUIC) += quic.o

quic-y := proto.o packet.o strm.o sock.o cid.o udp.o crypto.o \
	  input.o output.o frame.o sysctl.o
